/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototype.WizardBuilding;

import Prototype.StaticClasses.Global;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;
import org.jdom2.Element;
import javax.swing.JDialog;

/**
 *
 * @author User
 */
public class TemplateFormPopup extends javax.swing.JPanel {

    JDialog parent;
    boolean complete;
    Element Line;

    /**
     * Creates new form TemplateFormPopup
     */
    public TemplateFormPopup(JDialog Parent, ArrayList<String> Variables, int linenumber) {
        initComponents();
        DefaultComboBoxModel model = new DefaultComboBoxModel(Variables.toArray());
        Line = new Element("LINE" + linenumber);
        cboValues.setModel(model);
        complete = false;
        parent = Parent;
    }

    public TemplateFormPopup(JDialog Parent, ArrayList<String> Variables, Element line) {
        initComponents();

        Line = line;
        parent = Parent;
        HashMap<String, String> linemap = Global.makecommandmap(line.getAttributeValue("value"));
        String Caption = linemap.get("CAPTION");
        txtCaption.setText(Caption);
        String type = linemap.get("TYPE");
        complete = false;
        String text;
        switch (type) {
            case "PARAGRAPH":
                text = line.getChildText("TEXT");
                if (text != null) {
                    txtParagraph.setText(text);
                }
                this.rdoParagraph.setSelected(true);
                break;
            case "TEXT INPUT":
                text = linemap.get("DEFAULT");
                if (text != null) {
                    txtInput.setText(text);
                }
                this.rdoText.setSelected(true);
                break;
            case "LIST":
                TreeMap<Integer, String> listitems = new TreeMap();
                for (Element listitem : line.getChildren()) {
                    String name = listitem.getName();
                    if (name.startsWith("ITEM") && Global.isInteger(name.substring(4))) {
                        Integer itemnumber = Integer.parseInt(name.substring(4));
                        if (!listitems.containsKey(itemnumber) && itemnumber > 0) {
                            listitems.put(itemnumber, listitem.getText());
                        }
                    }
                }
                String listtext = "";
                for (Integer listnumber : listitems.keySet()) {
                    listtext = listtext + "\n" + listitems.get(listnumber);
                }
                if (listtext.length() > 1) {
                    this.txtList.setText(listtext.substring(1));
                }
                this.rdoList.setSelected(true);
                break;
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(Variables.toArray());
        cboValues.setModel(model);
        String store = linemap.get("STORE");
        if (store != null && model.getIndexOf(store) != -1) {
            cboValues.setSelectedItem(store);
        }
    }

    public Element getLine() {
        if (complete) {
            return Line;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputgroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCaption = new javax.swing.JTextField();
        rdoText = new javax.swing.JRadioButton();
        rdoParagraph = new javax.swing.JRadioButton();
        rdoList = new javax.swing.JRadioButton();
        txtInput = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboValues = new javax.swing.JComboBox();
        scrollpane1 = new javax.swing.JScrollPane();
        txtList = new javax.swing.JTextArea();
        scrollpane2 = new javax.swing.JScrollPane();
        txtParagraph = new javax.swing.JTextArea();

        jLabel1.setText("Caption:");

        txtCaption.setToolTipText("");

        inputgroup.add(rdoText);
        rdoText.setSelected(true);
        rdoText.setText("Text Input");
        rdoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTextActionPerformed(evt);
            }
        });

        inputgroup.add(rdoParagraph);
        rdoParagraph.setText("Display Paragraph");
        rdoParagraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoParagraphActionPerformed(evt);
            }
        });

        inputgroup.add(rdoList);
        rdoList.setText("Choose from List");
        rdoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoListActionPerformed(evt);
            }
        });

        txtInput.setText("Default Value");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("Store Result In:");

        cboValues.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboValuesActionPerformed(evt);
            }
        });

        txtList.setColumns(20);
        txtList.setRows(5);
        scrollpane1.setViewportView(txtList);

        txtParagraph.setColumns(20);
        txtParagraph.setRows(5);
        scrollpane2.setViewportView(txtParagraph);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoParagraph)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoList)
                            .addComponent(jLabel2)
                            .addComponent(rdoText)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInput)
                            .addComponent(scrollpane2)
                            .addComponent(scrollpane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboValues, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCaption))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtCaption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoText)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoParagraph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoList))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoListActionPerformed
        this.cboValues.setEnabled(true);
    }//GEN-LAST:event_rdoListActionPerformed

    private void rdoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTextActionPerformed
        this.cboValues.setEnabled(true);
    }//GEN-LAST:event_rdoTextActionPerformed

    private void cboValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboValuesActionPerformed
    }//GEN-LAST:event_cboValuesActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String Caption = txtCaption.getText();
        String linename = Line.getName();
        String Type;
        Line = new Element(linename);
        String commands = "";
        String store = this.cboValues.getSelectedItem().toString();
        if (rdoParagraph.isSelected()) {
            Type = "PARAGRAPH";
            String text = txtParagraph.getText();
            commands = "CAPTION:" + Caption + ";TYPE:" + Type + ";";
            Line.setAttribute("value", commands);
            Line.addContent(new Element("TEXT"));
            Line.getChild("TEXT").setText(text);
        } else if (rdoList.isSelected()) {
            Type = "LIST";
            commands = "CAPTION:" + Caption + ";TYPE:" + Type + ";STORE:" + store;
            String[] Listitems = txtList.getText().split("\\n");

            for (int counter = 1; counter <= Listitems.length; counter++) {
                Line.addContent(new Element("ITEM" + counter));
                Line.getChild("ITEM" + counter).setText(Listitems[counter-1]);
            }

        } else if (rdoText.isSelected()) {
            Type = "TEXT INPUT";
            String defaultvalue = txtInput.getText();
            commands = "CAPTION:" + Caption + ";TYPE:" + Type + ";DEFAULT:" + defaultvalue + ";STORE:" + store;
        }
        Line.setAttribute("value", commands);
        complete = true;
        parent.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        complete = false;
        parent.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void rdoParagraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoParagraphActionPerformed
        this.cboValues.setEnabled(false);
    }//GEN-LAST:event_rdoParagraphActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cboValues;
    private javax.swing.ButtonGroup inputgroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdoList;
    private javax.swing.JRadioButton rdoParagraph;
    private javax.swing.JRadioButton rdoText;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JScrollPane scrollpane2;
    private javax.swing.JTextField txtCaption;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextArea txtList;
    private javax.swing.JTextArea txtParagraph;
    // End of variables declaration//GEN-END:variables
}
